Next_Ticket_ID: 1
Assignee:
- INemesisI
- Admin
- Mod
Phrases:
  done: Erledigt!
  danke: Vielen Dank!
  gratulation: Herzlichen Glückwunsch!
  log: Benutze bitte /ticket log <#> <Nachricht> um auf das Ticket zu antworten!
  warp: Benutze bitte /ticket setwarp <#> dort, wo du Hilfe benötigst!
  gesichert: Deine Region wurde gesichert. Viel Spaß beim bauen!
  erweitert: Deine Region wurde erweitert. Viel Spaß!
  admin: Ein Admin wird sich darum kümmern!
  mod: Ein Mod wird sich darum kümmern!
