name: XcraftTickets

main: me.INemesisI.XcraftTickets.XcraftTickets

version: 1.3

load: POSTWORLD

commands:
  ticket:
    aliases: t
  tl:
    
permissions:
    XcraftTickets.Admin:
        description: Access to all /ticket commands this plugin provides
        children:
            XcraftTickets.Mod: true
            XcraftTickets.Save: true
            XcraftTickets.Reload: true
            XcraftTickets.Assignee: true
            XcraftTickets.Stats: true
        default: op
        
    XcraftTickets.Mod:
        description: Access to all mod related /ticket commands
        children:
            XcraftTickets.User: true
            XcraftTickets.Warp: true
            XcraftTickets.Assign: true
            XcraftTickets.Unassign: true
            XcraftTickets.List.All: true
            XcraftTickets.View.All: true
            XcraftTickets.Log.All: true
            XcraftTickets.Close.All: true
            XcraftTickets.Reopen.All: true
            XcraftTickets.Phrases: true
        default: false
        
    XcraftTickets.User:
        description: Access  to all user related /ticket commands
        children:
            XcraftTickets.Open: true
            XcraftTickets.Reopen: true
            XcraftTickets.Close: true
            XcraftTickets.List: true
            XcraftTickets.View: true
            XcraftTickets.Log: true
            XcraftTickets.Undo: true
            XcraftTickets.Setwarp: true
        default: true
    