name: XcraftTickets

main: me.INemesisI.XcraftTickets.XcraftTickets

version: 0.3

commands:
  ticket:
    usage:
  ti:
    usage:
  tk:
    usage:
  pe:
    usage:
    
permissions:
    XcraftTickets.Mod:
        description: Access to all /ticket commands
        children:
            XcraftTickets: true
        default: op
        
    XcraftTickets:
        description: Access to all user related /ticket commands